name: Build UsalDesk Windows

on:
  workflow_dispatch:

env:
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.6"

jobs:
  build-for-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Replace flutter engine
        run: |
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          mv -Force windows-x64-release/* C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/

      - name: Patch flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff $(dirname $(dirname $(which flutter)))
          cd $(dirname $(dirname $(which flutter)))
          git apply flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "1.75"
          targets: x86_64-pc-windows-msvc
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: windows-2022

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: C:\vcpkg\installed
          key: vcpkg-x64-windows-static-${{ env.VCPKG_COMMIT_ID }}

      - name: Install vcpkg dependencies
        shell: bash
        run: |
          $VCPKG_ROOT/vcpkg install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"

      - name: Flutter pub get
        run: |
          cd flutter
          flutter pub get
          cd ..

      - name: Generate bridge
        run: |
          cargo install flutter_rust_bridge_codegen --version 1.80.1 --locked
          flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart

      - name: Build Rust lib
        shell: bash
        run: |
          cargo build --features flutter --lib --release

      - name: Copy DLL to flutter
        shell: bash
        run: |
          cp target/release/librustdesk.dll flutter/windows/runner/

      - name: Build Flutter Windows
        run: |
          cd flutter
          flutter build windows --release

      - name: Prepare output
        shell: bash
        run: |
          mkdir -p ./usaldesk
          cp -r flutter/build/windows/x64/runner/Release/* ./usaldesk/

      - name: Build portable exe
        shell: bash
        run: |
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../usaldesk/ -o . -e ../../usaldesk/usaldesk.exe
          popd
          mkdir -p ./Output
          mv ./target/release/rustdesk-portable-packer.exe ./Output/UsalDesk-${{ env.VERSION }}-x86_64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: UsalDesk-Windows-x86_64
          path: ./Output/UsalDesk-${{ env.VERSION }}-x86_64.exe
